---
- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Download nginx RPM
  ansible.builtin.get_url:
    url: "{{ nginx_rpm_url }}"
    dest: "{{ nginx_rpm_path }}"
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install nginx from RPM
  ansible.builtin.yum:
    name: "{{ nginx_rpm_path }}"
    state: present
    disable_gpg_check: true
  when: ansible_os_family == "RedHat"

- name: Install git
  ansible.builtin.yum:
    name: git
    state: present
  when: ansible_os_family == "RedHat"

# - name: Remove lighthouse directory
#   ansible.builtin.file:
#     path: "{{ lighthouse_dir }}"
#     state: absent

- name: Create lighthouse directory
  ansible.builtin.file:
    path: "{{ lighthouse_dir }}"
    state: directory
    mode: '0755'

- name: Clone lighthouse repository
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    dest: "{{ lighthouse_dir }}"
    version: "{{ lighthouse_version }}"
    force: yes

- name: Create web root directory
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    mode: '0755'

- name: Copy lighthouse to web root
  ansible.builtin.copy:
    src: "{{ lighthouse_dir }}/"
    dest: "{{ web_root }}/"
    remote_src: true

#  добавил удаление def конфига, потому что...
- name: Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx

- name: Create nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    mode: '0644'
  notify: Restart nginx

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

