---
lighthouse_version: "master"
lighthouse_repo: "https://github.com/vegorshkov/lighthouse.git"
lighthouse_dir: "/opt/lighthouse"
web_root: "/usr/share/nginx/html/lighthouse"
nginx_config_path: "/etc/nginx/conf.d/lighthouse.conf"

nginx_rpm_url: "http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.24.0-1.el7.ngx.x86_64.rpm"
nginx_rpm_path: "/tmp/nginx.rpm"
