---
- name: Download Vector RPM
  ansible.builtin.get_url:
    url: "{{ vector_rpm_url }}"
    dest: "{{ vector_rpm_path }}"
    mode: '0644'

- name: Install Vector
  ansible.builtin.yum:
    name: "{{ vector_rpm_path }}"
    state: present
    disable_gpg_check: true
  notify: Restart vector

- name: Deploy Vector config
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: '0644'
  notify: Restart vector

- name: Start and enable Vector
  ansible.builtin.service:
    name: vector
    state: started
    enabled: true

