---
lighthouse_version: "latest"
lighthouse_repo: "https://github.com/vegorshkov/lighthouse.git"
lighthouse_dir: "/opt/lighthouse"
web_root: "/usr/share/nginx/html/lighthouse"
nginx_config_path: "/etc/nginx/conf.d/lighthouse.conf"

