---
vector_version: "0.34.0"
vector_rpm_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
vector_rpm_path: "/tmp/vector-{{ vector_version }}.rpm"
vector_config_path: "/etc/vector/vector.toml"

